version = 1
name = "development"
description = "Local software development environment"

[packages]
install = ["base-devel", "code", "distrobox", "github-cli", "nodejs", "npm", "podman", "python-pip", "rustup"]

[services]
enable = []

[configuration]
managed_files = []
