---
modules-search: [ local ]

instances:
  - id: online
    module: packages
    config: packages.conf
  - id: bootloader
    module: packagechooser
    config: packagechooser_bootloader.conf
  - id: desktop
    module: packagechooser
    config: packagechooser_desktop.conf
  - id: kernel
    module: packagechooser
    config: packagechooser_kernel.conf
  - id: graphics
    module: packagechooser
    config: packagechooser_graphics.conf
  - id: initialize
    module: shellprocess
    config: shellprocess_initialize.conf
  - id: finalize
    module: shellprocess
    config: shellprocess_finalize.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - packagechooser@bootloader
      - partition
      - packagechooser@desktop
      - packagechooser@kernel
      - packagechooser@graphics
      - netinstall
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@initialize
      - pacstrap
      - machineid
      - users
      - locale
      - keyboard
      - localecfg
      - packages@online
      - fstab
      - initcpiocfg
      - initcpio
      - networkcfg
      - displaymanager
      - hwclock
      - grubcfg
      - bootloader
      - services-systemd
      - shellprocess@finalize
      - umount
  - show:
      - finished

branding: najs
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
