---
efiBootLoaderVar: packagechooser_bootloader
efiBootLoader: systemd-boot
kernelSearchPath: /usr/lib/modules
kernelPattern: ^vmlinuz.*
loaderEntries: [ "timeout 5", "console-mode keep" ]
kernelParams: [ quiet, nowatchdog ]
refindKernelList: [ linux, linux-lts, linux-zen, linux-hardened ]
grubInstall: grub-install
grubMkconfig: grub-mkconfig
grubCfg: /boot/grub/grub.cfg
grubProbe: grub-probe
efiBootMgr: efibootmgr
efiBootloaderId: najs
installEFIFallback: true
installHybridGRUB: false
