---
extraMounts:
  - device: proc
    fs: proc
    mountPoint: /proc
  - device: sys
    fs: sysfs
    mountPoint: /sys
  - device: /dev
    mountPoint: /dev
    options: [ bind ]
  - device: tmpfs
    fs: tmpfs
    mountPoint: /run
  - device: /run/udev
    mountPoint: /run/udev
    options: [ bind ]
  - device: efivarfs
    fs: efivarfs
    mountPoint: /sys/firmware/efi/efivars
    efi: true

btrfsSubvolumes:
  - mountPoint: /
    subvolume: /roots/initial
  - mountPoint: /home
    subvolume: /home
  - mountPoint: /var/log
    subvolume: /var-log
  - mountPoint: /var/cache
    subvolume: /var-cache
  - mountPoint: /var/tmp
    subvolume: /var-tmp
  - mountPoint: /.snapshots
    subvolume: /snapshots

mountOptions:
  - filesystem: default
    options: [ defaults, noatime ]
  - filesystem: efi
    options: [ defaults, umask=0077 ]
  - filesystem: btrfs
    hddOptions: [ compress=zstd ]
    ssdOptions: [ compress=zstd ]
    nvmeOptions: [ compress=zstd:1 ]
    options: [ defaults, noatime ]
  - filesystem: ext4
    options: [ defaults, noatime ]
  - filesystem: xfs
    options: [ defaults, noatime, inode64 ]
  - filesystem: f2fs
    options: [ defaults, noatime ]
