---
basePackages:
  - base
  - linux-firmware
  - mkinitcpio
  - sudo
  - cryptsetup
  - device-mapper
  - dosfstools
  - e2fsprogs
  - xfsprogs
  - f2fs-tools
  - efibootmgr
  - grub
  - networkmanager
  - 7zip
  - alsa-firmware
  - ark
  - avahi
  - bash-completion
  - bluez-obex
  - bluez-utils
  - btop
  - btrfs-progs
  - cups
  - cups-pdf
  - cups-pk-helper
  - fastfetch
  - fd
  - firefox
  - firewalld
  - flatpak
  - fwupd
  - git
  - gnome-software
  - gst-plugin-pipewire
  - gst-plugins-bad
  - gst-plugins-good
  - gst-plugins-ugly
  - jq
  - keepassxc
  - man-pages
  - networkmanager-openvpn
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - power-profiles-daemon
  - qemu-guest-agent
  - ripgrep
  - sof-firmware
  - spice-vdagent
  - system-config-printer
  - ttf-liberation
  - unrar
  - unzip
  - virtualbox-guest-utils
  - wget
  - wireplumber
  - zenity
  - zip
postInstallFiles: []
