---
efiSystemPartition: /boot
efiSystemPartitionSize: 1024M
luksGeneration: luks2
userSwapChoices: [ none, small, suspend, file ]
drawNestedPartitions: true
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: btrfs
defaultPartitionTableType: gpt
availableFileSystemTypes: [ btrfs, ext4, xfs, f2fs ]
enableLuksAutomatedPartitioning: true

bootloaderOverrides:
  - name: grub
    defaultFileSystemType: btrfs
    availableFileSystemTypes: [ btrfs, ext4, xfs, f2fs ]
    efiSystemPartition: /boot/efi
    efiSystemPartitionSize: 1024M
    luksGeneration: luks2
  - name: systemd-boot
    defaultFileSystemType: btrfs
    availableFileSystemTypes: [ btrfs, ext4, xfs, f2fs ]
    efiSystemPartition: /boot
    efiSystemPartitionSize: 1024M
    luksGeneration: luks2
