---
dontChroot: true
script:
  - command: env CALAMARES_INSTALL=1 /usr/local/bin/najs-install --calamares-provision --target ${ROOT}
    timeout: 600
    verbose: true
i18n:
  name: Applying Najs platform configuration
