---
dontChroot: true
script:
  - command: pacman-key --init
    timeout: 120
  - command: pacman-key --populate archlinux
    timeout: 120
  - command: mkdir -p ${ROOT}/etc/pacman.d
  - command: cp /etc/pacman.conf ${ROOT}/etc/pacman.conf
  - command: cp /etc/pacman.d/mirrorlist ${ROOT}/etc/pacman.d/mirrorlist
  - command: cp -a /etc/pacman.d/gnupg ${ROOT}/etc/pacman.d/gnupg
  - command: cp -L /etc/resolv.conf ${ROOT}/etc/resolv.conf
i18n:
  name: Preparing trusted Arch Linux package sources
