---
defaultGroups: [ wheel, audio, video, storage, lp ]
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: false
passwordRequirements:
  minLength: 8
  libpwquality: [ minlen=8, minclass=2 ]
allowWeakPasswords: false
allowWeakPasswordsDefault: false
user:
  shell: /bin/bash
  home_permissions: o700
  forbidden_names: [ root, nobody, daemon, bin, systemd-network, systemd-timesync, dbus, polkitd ]
hostname:
  location: EtcFile
  writeHostsFile: true
  template: najs-${cpu}
  forbidden_names: [ localhost ]
allowActiveDirectory: false
