---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredStorage: 32.0
  requiredRam: 2.0
  internetCheckUrl: https://archlinux.org/
  check: [ storage, ram, power, internet, root, screen ]
  required: [ storage, ram, internet, root ]

geoip:
  style: none
  url: ""
  selector: ""
